credentials:
  usernames:
    # User 1
    user1:
      name: "user"
      password: "vasco#2925"
cookie:
  name: "streamlit_auth_cookie"
  key: "SOME_RANDOMLY_GENERATED_KEY"
  expiry_days: 1
