credentials:
  usernames:
    # User 1
    user1:
      name: "User1"
      password: "passwort1"
    # User 2
    user2:
      name: "User2"
      password: "passwort2"
cookie:
  name: "streamlit_auth_cookie"
  key: "SOME_RANDOMLY_GENERATED_KEY"
  expiry_days: 1
